### ISSUE TITLE
SLP-SDK overwrites trest to rest

### ISSUE THREAD

**Issue by christroutner** [Bitcoin-com/slp-sdk#19]
Attempting to initialize SLP to testnet like this:

`let slp = new SLP({ restURL: 'https://trest.bitcoin.com/v2/' })`

Will fail. SLP will actually initialize to `rest`.

The scope of this Issue is to investigate and see what may be preventing SLP-SDK from initializing to trest.

**Comment by cgcardona** [comment]
I'm unable to reproduce this. The following works properly for me

```
let SLPSDK = require("slp-sdk/lib/SLP").default;
let SLP = new SLPSDK({
  restURL: "https://trest.bitcoin.com/v2/"
});

// fetch details of testnet token
(async () => {
  try {
    let list = await SLP.Utils.list(
      "24686f336975796253be67ab3d6b1b304905f0f5d81fa934c581aba4da606f38"
    );
    console.log(list);
  } catch (error) {
    console.error(error);
  }
})();
```

**Comment by christroutner** [comment]
I also could not reproduce this bug. It must have gotten fixed in one of the other code updates.
