### ISSUE TITLE
Need to throw errors, not return them

### ISSUE THREAD

**Issue by christroutner** [Bitcoin-com/slp-sdk#27]
The libraries in SLP SDK are riddled with the pattern of `return error` instead of `throw error`. Returning an error will not trigger an error handler. [Here is an example](https://github.com/Bitcoin-com/slp-sdk/blob/92dab7786f2ece5fc315e4ca9980330e5fe46b21/lib/Address.js#L74)

The scope of this Issue is to refactor all the libraries in SLP SDK and replace instances of `return error` with `throw error`.

**Comment by cgcardona** [comment]
This is resolved in SLP SDK v4.4.1
