### ISSUE TITLE
Use REST validateTxid method instead of LocalValidator

### ISSUE THREAD

**Issue by jcramer** [Bitcoin-com/slp-sdk#31]
Within `TokenType1.ts` none of the methods are utilizing the `/slp/validateTxid` endpoint which will perform much faster than `LocalValidator`.

**Comment by christroutner** [comment]
Idea to explore: Could we implement a constant like `OFFLINE`, where if true is uses LocalValidator, and if not, makes calls to rest? Does that make any sense? I'm trying to think of use cases in which people would *want* to use the local validator. Maybe that doesn't make sense?

**Comment by jcramer** [comment]
Agree it will important to allow the user to override validator instance.

Check out the readme updates for SLPJS 0.15.9, I think this dramatically simplifies thing for consumers while providing the desired flexibility.

https://github.com/simpleledger/slpjs/commit/a46b5c904336b216c0bd306946170532ab0d2a8e

**Comment by jcramer** [comment]
this has been resolved
